export const SINGLE_DUMMY_USERS = [
  {
    id: "u1",
    name: "John Doe",
    nationality: "United States",
    location: "Bangkok, Thailand",
    education: "Bachelor of Education, Chulalongkorn University",
    workExperience: "5 years teaching experience",
    interests: ["Teaching", "Traveling", "Photography"],
    bio: "Hi, my name is John and I am originally from Bakalashaka, Minnesota. Never heard of it? Well, that's because it's a small town in bumbleF*&# minny SOTAAAA YEAH BOII",
    skill: ["student-centered", "PPP", "lesson planning"],
    resume: [
      {
        resumeId: 1,
        company: "Bright Future",
        schoolName: "Bright Future International",
        role: "teach m1 and m2 conversational English",
        location: "Bangkok, Thailand",
        jobTitle: "English Teacher",
        from: 2004,
        to: 2012,
      },
      {
        resumeId: 2,
        company: "GunChunk GooJang",
        schoolName: "Korea University English Pg",
        role: "Teach university students business English",
        location: "Seoul, South korea",
        jobTitle: "English Teacher",
        from: 2002,
        to: 2004,
      },
      {
        resumeId: 3,
        company: "Bright Future",
        schoolName: "Bright Future International",
        role: "teach m1 and m2 conversational English",
        location: "Bangkok, Thailand",
        jobTitle: "English Teacher",
        from: 2000,
        to: 2002,
      },
    ],
  },
];

export const DUMMY_USERS_LIST = [
  {
    id: "u1",
    name: "John Doe",
    location: "Bangkok, Thailand",
    education: "Bachelor of Education, Chulalongkorn University",
    workExperience: "5 years teaching experience",
    interests: ["Teaching", "Traveling", "Photography"],
  },
  {
    id: "u2",
    name: "Michael Hunter",
    location: "Bangkok, Thailand",
    education: "Bachelor of Education, Chulalongkorn University",
    workExperience: "9 years teaching experience",
    interests: ["Teaching", "Traveling", "Photography"],
  },
  {
    id: "u3",
    name: "Bob McFarland",
    location: "Bangkok, Thailand",
    education: "Bachelor of Education, Chulalongkorn University",
    workExperience: "2 years teaching experience",
    interests: ["Teaching", "Traveling", "Photography"],
  },
  {
    id: "u4",
    name: "Janitha Willdubs",
    location: "Bangkok, Thailand",
    education: "Bachelor of Education, Chulalongkorn University",
    workExperience: "1 years teaching experience",
    interests: ["Teaching", "Traveling", "Photography"],
  },
];
