//current list of cities
export const thaiCities = [
  "Bangkok",
  "Chiang Mai",
  "Phuket",
  "Pattaya",
  "Krabi",
  "Koh Samui",
  "Hua Hin",
  "Ayutthaya",
  "Kanchanaburi",
  "Nakhon Ratchasima",
  "Chonburi",
  "Udon Thani",
  "Surat Thani",
  "Ubon Ratchathani",
  "Trang",
  "Rayong",
  "Khon Kaen",
  "Phitsanulok",
  "Nakhon Si Thammarat",
  "Sukhothai",
  "Nong Khai",
  "Ranong",
  "Chumphon",
  "Samut Prakan",
  "Samut Sakhon",
  "Nakhon Pathom",
  "Songkhla",
  "Yala",
  "Satun",
  "Narathiwat",
  "Trat",
];

//list of fulltime incomes
export const fullTimeSalaries = [
  "at least THB 20k/mo.",
  "THB 30k/mo.",
  "THB 40k/mo.",
  "THB 50k/mo.",
  "THB 60k/mo.",
  "THB 70k/mo.",
  "THB 80k/mo.",
  "THB 90k/mo.",
  "over THB 100k/mo.",
];

//list of partime incomes.
export const partTimeSalaries = [
  "at least 250THB/hour",
  "THB 300/hour",
  "THB 400/hour",
  "THB 500/hour",
  "THB 600/hour",
  "THB 700/hour",
  "THB 800/hour",
  "THB 900/hour",
  "over THB 1000/hour",
];
